### ISSUE TITLE
will this project detect circular dependency?

### ISSUE THREAD

**Issue by zjsxwc** [golobby/container#11]
i am looking for an ioc container that can solve circular dependency.

i cannot  find source code which do detect circular dependency  from the project.

anyway, this project design is a very useful example for me, thank you!

**Comment by amirrezaask** [comment]
If I am right you are talking about a situation where package A imports B and vice versa.
Since go compiler itself detects circular dependencies and does not allow compilation to continue I don't see the use of golobby/container detecting circular dependencies itself.
There is the possibility for container to be able to solve circular dependencies problem but that is not possible without either changing codebase automatically or dive into golang compiler itself which will make container so much complex.
Since one of the goals behind golobby packages was to be simplest solution possible I don't think solving circular dependency is a good feature to add into container

**Comment by zjsxwc** [comment]
i dont mean the situation where package A imports B and vice versa.

i mean the situation in the ioc container.

and i find that the dig project solved the problem, see:
https://godoc.org/go.uber.org/dig#IsCycleDetected
